import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
    MessageCircle, X, Send, HelpCircle, ArrowRight, Sparkles, 
    ChevronRight, BookOpen, Clock, Calendar, FileText, UserCircle 
} from 'lucide-react';
import { useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

const AI_KNOWLEDGE_BASE = {
    general: [
        { q: "How do I mark attendance?", a: "To mark attendance, go to the 'Attendance' page, select 'Today's Attendance', and click the 'Mark Entry' or 'Mark Exit' button.", link: "/staff/attendance" },
        { q: "How to apply for leave?", a: "Navigate to 'Leaves', then 'Leave Application'. Fill out the form with your dates and reason, then submit for approval.", link: "/staff/leave-apply" },
        { q: "How to view reports?", a: "Go to 'Reports' section from your sidebar to see detailed analytics of your activities.", link: "/staff/reports" }
    ],
    admin: [
        { q: "How to manage employees?", a: "Click 'Employee Management' in your sidebar. From there, you can Add, Edit, or Remove staff members.", link: "/admin/employees" },
        { q: "How to approve leaves?", a: "Go to 'Leave Approvals' to see a list of pending requests from all departments.", link: "/admin/approvals" },
        { q: "System Settings?", a: "Access 'Settings' to update company information, VAPID keys, or SMTP configurations.", link: "/admin/settings" }
    ],
    staff: [
        { q: "Check my salary?", a: "You can view your salary slips in the 'Payroll' section once they are generated by HR.", link: "/staff/payroll" },
        { q: "Update profile image?", a: "Go to 'Profile Settings' and click on your avatar to upload a new professional photo.", link: "/staff/profile" }
    ]
};

const PAGE_CONTEXTS = {
    '/attendance': "You are on the Attendance page. Here you can track your daily punches and biometric sync status.",
    '/leave-apply': "You are on the Leave Application page. Select your leave type and dates to start a request.",
    '/dashboard': "Welcome to your Hub Dashboard. You can see a summary of your attendance and recent notifications here.",
    '/admin': "You are in the Admin Control Center. Use the sidebar to manage system-wide data."
};

const AiAssistant = () => {
    const { user } = useAuth();
    const location = useLocation();
    const navigate = useNavigate();
    const [isOpen, setIsOpen] = useState(false);
    const [messages, setMessages] = useState([
        { type: 'ai', text: `Hello ${user?.name || 'there'}! I am your PPG iTech Assistant. How can I help you today?`, time: new Date() }
    ]);
    const [input, setInput] = useState('');
    const [suggestions, setSuggestions] = useState([]);
    const scrollRef = useRef(null);

    // Context & Role Awareness
    useEffect(() => {
        const role = user?.role?.toLowerCase() || 'staff';
        const roleSuggestions = AI_KNOWLEDGE_BASE[role] || [];
        const baseSuggestions = AI_KNOWLEDGE_BASE.general;
        
        // Combine and limit to 4 suggestions
        setSuggestions([...baseSuggestions, ...roleSuggestions].slice(0, 4));

        // Auto-message when page changes
        const path = location.pathname;
        if (PAGE_CONTEXTS[path] && isOpen) {
            setMessages(prev => [...prev, {
                type: 'ai',
                text: PAGE_CONTEXTS[path],
                time: new Date(),
                isContext: true
            }]);
        }
    }, [location.pathname, user?.role, isOpen]);

    useEffect(() => {
        if (scrollRef.current) {
            scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
        }
    }, [messages]);

    const handleSend = (text = input) => {
        if (!text.trim()) return;

        const newMsg = { type: 'user', text, time: new Date() };
        setMessages(prev => [...prev, newMsg]);
        setInput('');

        // Simple AI Logic Simulated
        setTimeout(() => {
            let reply = "I'm sorry, I don't have specific info on that yet, but you can try the suggested questions below!";
            let actionLink = null;

            // Search in knowledge base
            const allKnowledge = [...AI_KNOWLEDGE_BASE.general, ...(AI_KNOWLEDGE_BASE[user?.role?.toLowerCase()] || [])];
            const match = allKnowledge.find(k => text.toLowerCase().includes(k.q.toLowerCase()) || k.q.toLowerCase().includes(text.toLowerCase()));

            if (match) {
                reply = match.a;
                actionLink = match.link;
            }

            setMessages(prev => [...prev, { 
                type: 'ai', 
                text: reply, 
                link: actionLink,
                time: new Date() 
            }]);
        }, 800);
    };

    if (!user) return null; // Don't show on login page

    return (
        <div className="fixed bottom-6 right-6 z-[10000]">
            <AnimatePresence>
                {isOpen && (
                    <motion.div
                        initial={{ opacity: 0, scale: 0.8, y: 50 }}
                        animate={{ opacity: 1, scale: 1, y: 0 }}
                        exit={{ opacity: 0, scale: 0.8, y: 50 }}
                        className="mb-4 w-[350px] max-h-[500px] bg-white rounded-[32px] shadow-[0_20px_50px_rgba(0,104,255,0.15)] flex flex-col overflow-hidden border border-sky-50"
                    >
                        {/* Header */}
                        <div className="bg-gradient-to-r from-sky-600 to-sky-500 p-5 flex items-center justify-between">
                            <div className="flex items-center gap-3">
                                <div className="h-10 w-10 bg-white/20 backdrop-blur-md rounded-2xl flex items-center justify-center border border-white/20">
                                    <Sparkles className="text-white h-5 w-5 animate-pulse" />
                                </div>
                                <div>
                                    <h3 className="text-white font-black text-sm tracking-tight">AI Assistant</h3>
                                    <div className="flex items-center gap-1.5">
                                        <div className="h-1.5 w-1.5 bg-emerald-400 rounded-full animate-bounce" />
                                        <span className="text-sky-100 text-[9px] font-bold uppercase tracking-widest">Always Active</span>
                                    </div>
                                </div>
                            </div>
                            <button 
                                onClick={() => setIsOpen(false)}
                                className="p-2 hover:bg-white/10 rounded-xl transition-colors text-white"
                            >
                                <X size={20} />
                            </button>
                        </div>

                        {/* Chat Body */}
                        <div 
                            ref={scrollRef}
                            className="flex-1 overflow-y-auto p-5 space-y-4 bg-sky-50/30 scroll-smooth"
                            style={{ maxHeight: '300px' }}
                        >
                            {messages.map((m, i) => (
                                <motion.div
                                    key={i}
                                    initial={{ opacity: 0, x: m.type === 'ai' ? -10 : 10 }}
                                    animate={{ opacity: 1, x: 0 }}
                                    className={`flex ${m.type === 'ai' ? 'justify-start' : 'justify-end'}`}
                                >
                                    <div className={`max-w-[85%] p-3.5 rounded-2xl text-[12px] font-bold leading-relaxed shadow-sm ${
                                        m.type === 'ai' 
                                            ? 'bg-white text-gray-700 rounded-tl-none border border-sky-100' 
                                            : 'bg-sky-600 text-white rounded-tr-none'
                                    }`}>
                                        {m.text}
                                        {m.link && (
                                            <button 
                                                onClick={() => { navigate(m.link); setIsOpen(false); }}
                                                className="mt-3 flex items-center gap-2 text-sky-600 bg-sky-50 px-3 py-2 rounded-xl text-[10px] w-full font-black border border-sky-100/50 hover:bg-sky-100 transition-colors"
                                            >
                                                Take Me There <ChevronRight size={14} />
                                            </button>
                                        )}
                                    </div>
                                </motion.div>
                            ))}
                        </div>

                        {/* Suggestions */}
                        {suggestions.length > 0 && (
                            <div className="p-4 bg-white border-t border-sky-50">
                                <p className="text-[9px] font-black text-sky-400 uppercase tracking-widest mb-3 flex items-center gap-1.5">
                                    <HelpCircle size={12} /> Suggestions for you
                                </p>
                                <div className="flex flex-wrap gap-2">
                                    {suggestions.map((s, i) => (
                                        <button
                                            key={i}
                                            onClick={() => handleSend(s.q)}
                                            className="text-[10px] font-bold text-sky-600 bg-sky-50 px-3 py-1.5 rounded-full hover:bg-sky-100 border border-sky-100 transition-all hover:scale-105"
                                        >
                                            {s.q}
                                        </button>
                                    ))}
                                </div>
                            </div>
                        )}

                        {/* Footer / Input */}
                        <div className="p-4 bg-white border-t border-sky-50">
                            <form 
                                onSubmit={(e) => { e.preventDefault(); handleSend(); }}
                                className="flex items-center gap-2 bg-sky-50 p-1.5 rounded-2xl border border-sky-100"
                            >
                                <input 
                                    type="text"
                                    value={input}
                                    onChange={(e) => setInput(e.target.value)}
                                    placeholder="Type your question..."
                                    className="flex-1 bg-transparent border-none outline-none px-3 text-xs font-bold text-gray-700 placeholder:text-gray-400"
                                />
                                <button 
                                    type="submit"
                                    className="bg-sky-600 p-2.5 rounded-xl text-white shadow-lg shadow-sky-200 hover:bg-sky-700 transition-all active:scale-95"
                                >
                                    <Send size={16} />
                                </button>
                            </form>
                        </div>
                    </motion.div>
                )}
            </AnimatePresence>

            {/* Float Button */}
            <motion.button
                whileHover={{ scale: 1.05, rotate: 5 }}
                whileTap={{ scale: 0.95 }}
                onClick={() => setIsOpen(!isOpen)}
                className={`h-14 w-14 rounded-2xl flex items-center justify-center shadow-2xl transition-all duration-300 ${
                    isOpen ? 'bg-white text-sky-600' : 'bg-sky-600 text-white animate-bounce-slow'
                }`}
                style={{ boxShadow: isOpen ? '0 10px 40px rgba(0,0,0,0.1)' : '0 10px 30px rgba(14, 165, 233, 0.4)' }}
            >
                {isOpen ? <X size={24} /> : <MessageCircle size={24} />}
            </motion.button>
            <style dangerouslySetInnerHTML={{ __html: `
                @keyframes bounce-slow {
                    0%, 100% { transform: translateY(0); }
                    50% { transform: translateY(-10px); }
                }
                .animate-bounce-slow {
                    animation: bounce-slow 4s infinite ease-in-out;
                }
            `}} />
        </div>
    );
};

export default AiAssistant;
