import { useState, useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import Sidebar from './Sidebar';
import Header from './Header';
import { useAuth } from '../context/AuthContext';

const Layout = ({ children }) => {
    const [sidebarOpen, setSidebarOpen] = useState(false);
    const { user, loading } = useAuth();
    const location = useLocation();

    const isManagement = location.pathname.startsWith('/management');
    const effectiveRole = isManagement ? 'management' : (user?.role || 'staff');

    useEffect(() => {
        const handleCloseSidebar = () => setSidebarOpen(false);
        window.addEventListener('closeSidebar', handleCloseSidebar);
        return () => window.removeEventListener('closeSidebar', handleCloseSidebar);
    }, []);

    if (loading && !isManagement) return <div className="h-screen w-screen flex items-center justify-center bg-sky-50">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-sky-600"></div>
    </div>;

    return (
        <div className="flex h-screen bg-transparent overflow-hidden font-sans">
            {/* Sidebar */}
            <Sidebar
                userRole={effectiveRole}
                isOpen={sidebarOpen}
                onToggle={() => setSidebarOpen(!sidebarOpen)}
                onClose={() => setSidebarOpen(false)}
            />

            {/* Backdrop for mobile */}
            {sidebarOpen && (
                <div
                    className="fixed inset-0 bg-sky-900/20 backdrop-blur-sm lg:hidden z-30 transition-all duration-500"
                    onClick={() => setSidebarOpen(false)}
                />
            )}

            <div className={`flex-1 flex flex-col overflow-hidden transition-all duration-500 ease-in-out ${sidebarOpen ? 'lg:ml-64' : 'ml-0'}`}>
                <Header
                    toggleSidebar={() => setSidebarOpen(!sidebarOpen)}
                    sidebarOpen={sidebarOpen}
                />

                <main className="flex-1 overflow-x-hidden overflow-y-auto p-4 md:p-8 no-scrollbar scroll-smooth">
                    <div className="max-w-7xl mx-auto space-y-6 animate-fade-in relative z-10">
                        {/* Print-Only Branding Header */}
                        <div className="print-branding-header hidden print:block mb-8 border-b-4 border-black pb-4 text-black">
                            <div className="flex justify-between items-end">
                                <div>
                                    <p className="text-[10px] font-black uppercase tracking-[0.3em]">Staff Management System</p>
                                </div>
                                <div className="text-right">
                                    <p className="text-sm font-black text-blue-900" style={{ letterSpacing: '0.5px' }}>PPG iTech HUB</p>
                                    <p className="text-[9px] font-bold text-gray-500">{new Date().toLocaleString('en-GB')}</p>
                                </div>
                            </div>
                            <div className="mt-4 pt-4 border-t border-gray-100 flex justify-between items-center text-[9px] font-bold uppercase tracking-widest">
                                <span>Generated by: {isManagement ? 'Management' : user?.name}</span>
                                <span>Role Authority: {effectiveRole}</span>
                            </div>
                        </div>

                        {children}
                    </div>
                </main>
            </div>
        </div>
    );
};

export default Layout;
